apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: core-vpa
  namespace: voucher-management-app
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: voucher-app-core
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        minAllowed:
          cpu: 100m
          memory: 250Mi
        maxAllowed:
          cpu: 350m
          memory: 500Mi
        controlledResources: ["cpu", "memory"]
