apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: auth-vpa
  namespace: voucher-management-app
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: voucher-app-auth
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        minAllowed:
          cpu: 100m
          memory: 200Mi
        maxAllowed:
          cpu: 300m
          memory: 400Mi
        controlledResources: ["cpu", "memory"]
